language: ruby
before_install: rm Gemfile.lock || true
rvm:
  - 1.8.7
  - 1.9.3
script:
  - "rake spec SPEC_OPTS='--format documentation'"
env:
  - PUPPET_VERSION="~> 3.1.0"
  - PUPPET_VERSION="~> 3.3.0"
  - PUPPET_VERSION="~> 3.6.0"

gemfile: .gemfile
sudo: false
notifications:
  email:
    - al@lab42.it
