language: ruby
before_install: rm .gemfile.lock || true
rvm:
  - 1.8.7
  - 1.9.3
  - 2.1.4
script:
  - "bundle exec rake syntax lint spec SPEC_OPTS='--format documentation'"
env:
  - PUPPET_VERSION="~> 3.1.0"
  - PUPPET_VERSION="~> 3.3.0"
  - PUPPET_VERSION="~> 3.6.0"
  - PUPPET_VERSION="~> 4.2"
matrix:
  exclude:
    - rvm: 1.8.7
      env: PUPPET_VERSION="~> 4.2"
    - rvm: 2.1.4
      env: PUPPET_VERSION="~> 3.1.0"
    - rvm: 2.1.4
      env: PUPPET_VERSION="~> 3.3.0"

gemfile: .gemfile
sudo: false
notifications:
  email:
    - al@lab42.it
